// NOTE: This file is completely generated by AI because I could not be bothered to go through over 100 types manually. The code is all human tested and reviewed

#include "jsonConverter.hpp"
#include <stdexcept>

// Serialize an optional value: skip key when nullopt, emit value otherwise.
template <typename T>
static void opt_to_json(nlohmann::json &j, const char *key, const std::optional<T> &v)
{
  if (v.has_value())
    j[key] = *v;
}

namespace General
{

  void to_json(nlohmann::json &j, const MotionController &v)
  {
    j["type"] = v.type;
  }

  void to_json(nlohmann::json &j, const ValueToParameterMapping &v)
  {
    j["valueType"] = v.valueType;
    j["fromValue"] = v.fromValue;
    j["toParameter"] = v.toParameter;
  }

  namespace ISensorEntityPrioritiser
  {
    void to_json(nlohmann::json &j, const ISensorEntityPrioritiser & /*v*/)
    {
      j = nlohmann::json::object();
    }

    void to_json(nlohmann::json &j, const Attitude &v)
    {
      j["attitudesByPriority"] = v.attitudesByPriority;
    }
  }

  namespace ISensorEntityCollector
  {
    void to_json(nlohmann::json &j, const ISensorEntityCollector & /*v*/)
    {
      j = nlohmann::json::object();
    }

    void to_json(nlohmann::json &j, const CombatTargets & /*v*/)
    {
      j = nlohmann::json::object();
    }
  }

  namespace IEntityFilter
  {
    void to_json(nlohmann::json &j, const IEntityFilter &v)
    {
      j["type"] = v.type;
    }

    void to_json(nlohmann::json &j, const Altitude &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      j["altitudeRange"] = v.altitudeRange;
    }

    void to_json(nlohmann::json &j, const And &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      j["filters"] = v.filters;
    }

    void to_json(nlohmann::json &j, const Attitude &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      j["attitudes"] = v.attitudes;
    }

    void to_json(nlohmann::json &j, const Combat &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "sequence", v.sequence);
      opt_to_json(j, "timeElapsedRange", v.timeElapsedRange);
      opt_to_json(j, "mode", v.mode);
    }

    void to_json(nlohmann::json &j, const Flock &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "flockStatus", v.flockStatus);
      opt_to_json(j, "flockPlayerStatus", v.flockPlayerStatus);
      opt_to_json(j, "size", v.size);
      opt_to_json(j, "checkCanJoin", v.checkCanJoin);
    }

    void to_json(nlohmann::json &j, const HeightDifference &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "heightDifference", v.heightDifference);
      opt_to_json(j, "useEyePosition", v.useEyePosition);
    }

    void to_json(nlohmann::json &j, const InsideBlock &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      j["blockSet"] = v.blockSet;
    }

    void to_json(nlohmann::json &j, const Inventory &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "items", v.items);
      opt_to_json(j, "countRange", v.countRange);
      opt_to_json(j, "freeSlotRange", v.freeSlotRange);
    }

    void to_json(nlohmann::json &j, const ItemInHand &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "items", v.items);
      opt_to_json(j, "hand", v.hand);
    }

    void to_json(nlohmann::json &j, const LineOfSight &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const MovementState &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      j["state"] = v.state;
    }

    void to_json(nlohmann::json &j, const NPCGroup &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "includeGroups", v.includeGroups);
      opt_to_json(j, "excludeGroups", v.excludeGroups);
    }

    void to_json(nlohmann::json &j, const Not &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      j["filter"] = v.filter;
    }

    void to_json(nlohmann::json &j, const Or &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      j["filters"] = v.filters;
    }

    void to_json(nlohmann::json &j, const SpotsMe &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "viewAngle", v.viewAngle);
      opt_to_json(j, "viewTest", v.viewTest);
      opt_to_json(j, "testLineOfSight", v.testLineOfSight);
    }

    void to_json(nlohmann::json &j, const StandingOnBlock &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "blockSet", v.blockSet);
    }

    void to_json(nlohmann::json &j, const Stat &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      j["stat"] = v.stat;
      j["statTarget"] = v.statTarget;
      j["relativeTo"] = v.relativeTo;
      j["relativeToTarget"] = v.relativeToTarget;
      j["valueRange"] = v.valueRange;
    }

    void to_json(nlohmann::json &j, const ViewSector &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "viewSector", v.viewSector);
    }
  }

  namespace Sensor
  {
    // Helper: emit the concrete sensor fields into j given a base reference.
    nlohmann::json sensorToJson(const Sensor &s)
    {
      nlohmann::json j;
      j["type"] = s.type;
      switch (s.type)
      {
      case Type::AdjustPosition:
        j = static_cast<const AdjustPosition &>(s);
        break;
      case Type::Age:
        j = static_cast<const Age &>(s);
        break;
      case Type::Alarm:
        j = static_cast<const Alarm &>(s);
        break;
      case Type::And:
        j = static_cast<const And &>(s);
        break;
      case Type::Animation:
        j = static_cast<const Animation &>(s);
        break;
      case Type::Any:
        j = static_cast<const Any &>(s);
        break;
      case Type::Beacon:
        j = static_cast<const Beacon &>(s);
        break;
      case Type::BlockChange:
        j = static_cast<const BlockChange &>(s);
        break;
      case Type::BlockType:
        j = static_cast<const BlockType &>(s);
        break;
      case Type::CanInteract:
        j = static_cast<const CanInteract &>(s);
        break;
      case Type::CanPlaceBlock:
        j = static_cast<const CanPlaceBlock &>(s);
        break;
      case Type::CombatActionEvaluator:
        j = static_cast<const CombatActionEvaluator &>(s);
        break;
      case Type::Count:
        j = static_cast<const Count &>(s);
        break;
      case Type::Damage:
        j = static_cast<const Damage &>(s);
        break;
      case Type::DroppedItem:
        j = static_cast<const DroppedItem &>(s);
        break;
      case Type::EntityEvent:
        j = static_cast<const EntityEvent &>(s);
        break;
      case Type::Flag:
        j = static_cast<const Flag &>(s);
        break;
      case Type::FlockCombatDamage:
        j = static_cast<const FlockCombatDamage &>(s);
        break;
      case Type::FlockLeader:
        j = static_cast<const FlockLeader &>(s);
        break;
      case Type::HasHostileTargetMemory:
        j = static_cast<const HasHostileTargetMemory &>(s);
        break;
      case Type::HasInteracted:
        j = static_cast<const HasInteracted &>(s);
        break;
      case Type::HasTask:
        j = static_cast<const HasTask &>(s);
        break;
      case Type::InAir:
        j = static_cast<const InAir &>(s);
        break;
      case Type::InWater:
        j = static_cast<const InWater &>(s);
        break;
      case Type::InflictedDamage:
        j = static_cast<const InflictedDamage &>(s);
        break;
      case Type::InteractionContext:
        j = static_cast<const InteractionContext &>(s);
        break;
      case Type::IsBackingAway:
        j = static_cast<const IsBackingAway &>(s);
        break;
      case Type::IsBusy:
        j = static_cast<const IsBusy &>(s);
        break;
      case Type::Kill:
        j = static_cast<const Kill &>(s);
        break;
      case Type::Leash:
        j = static_cast<const Leash &>(s);
        break;
      case Type::Light:
        j = static_cast<const Light &>(s);
        break;
      case Type::Mob:
        j = static_cast<const Mob &>(s);
        break;
      case Type::Nav:
        j = static_cast<const Nav &>(s);
        break;
      case Type::Not:
        j = static_cast<const Not &>(s);
        break;
      case Type::OnGround:
        j = static_cast<const OnGround &>(s);
        break;
      case Type::Or:
        j = static_cast<const Or &>(s);
        break;
      case Type::Path:
        j = static_cast<const Path &>(s);
        break;
      case Type::Player:
        j = static_cast<const Player &>(s);
        break;
      case Type::Random:
        j = static_cast<const Random &>(s);
        break;
      case Type::ReadPosition:
        j = static_cast<const ReadPosition &>(s);
        break;
      case Type::SearchRay:
        j = static_cast<const SearchRay &>(s);
        break;
      case Type::Self:
        j = static_cast<const Self &>(s);
        break;
      case Type::State:
        j = static_cast<const State &>(s);
        break;
      case Type::Switch:
        j = static_cast<const Switch &>(s);
        break;
      case Type::Target:
        j = static_cast<const Target &>(s);
        break;
      case Type::Time:
        j = static_cast<const Time &>(s);
        break;
      case Type::Timer:
        j = static_cast<const Timer &>(s);
        break;
      case Type::ValueProviderWrapper:
        j = static_cast<const ValueProviderWrapper &>(s);
        break;
      case Type::Weather:
        j = static_cast<const Weather &>(s);
        break;
      }
      return j;
    }

    void to_json(nlohmann::json &j, const Sensor &v) { j = sensorToJson(v); }

    void to_json(nlohmann::json &j, const AdjustPosition &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      if (v.sensor != nullptr)
        j["sensor"] = sensorToJson(*v.sensor);
      j["offset"] = v.offset;
    }

    void to_json(nlohmann::json &j, const Age &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["ageRange"] = v.ageRange;
    }

    void to_json(nlohmann::json &j, const Alarm &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["name"] = v.name;
      j["state"] = v.state;
      opt_to_json(j, "clear", v.clear);
    }

    void to_json(nlohmann::json &j, const And &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      nlohmann::json arr = nlohmann::json::array();
      for (const auto &s : v.sensors)
        arr.push_back(sensorToJson(*s));
      j["sensors"] = arr;
      opt_to_json(j, "autoUnlockTargetSlot", v.autoUnlockTargetSlot);
    }

    void to_json(nlohmann::json &j, const Animation &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["slot"] = v.slot;
      j["animation"] = v.animation;
    }
    void to_json(nlohmann::json &j, const Any &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const Beacon &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["message"] = v.message;
      opt_to_json(j, "range", v.range);
      opt_to_json(j, "targetSlot", v.targetSlot);
      opt_to_json(j, "consumeMessage", v.consumeMessage);
    }

    void to_json(nlohmann::json &j, const BlockChange &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["range"] = v.range;
      j["searchType"] = v.searchType;
      opt_to_json(j, "targetSlot", v.targetSlot);
      j["blockSet"] = v.blockSet;
      opt_to_json(j, "eventType", v.eventType);
    }

    void to_json(nlohmann::json &j, const BlockType &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      if (v.sensor != nullptr)
        j["sensor"] = sensorToJson(*v.sensor);
      j["blockSet"] = v.blockSet;
    }

    void to_json(nlohmann::json &j, const CanInteract &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["viewSector"] = v.viewSector;
      j["attitudes"] = v.attitudes;
    }

    void to_json(nlohmann::json &j, const CanPlaceBlock &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["direction"] = v.direction;
      opt_to_json(j, "offset", v.offset);
      opt_to_json(j, "retryDelay", v.retryDelay);
      opt_to_json(j, "allowEmptyMaterials", v.allowEmptyMaterials);
    }

    void to_json(nlohmann::json &j, const CombatActionEvaluator &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["targetInRange"] = v.targetInRange;
      opt_to_json(j, "allowableDeviation", v.allowableDeviation);
    }

    void to_json(nlohmann::json &j, const Count &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["count"] = v.count;
      j["range"] = v.range;
      opt_to_json(j, "includeGroups", v.includeGroups);
      opt_to_json(j, "excludeGroups", v.excludeGroups);
    }

    void to_json(nlohmann::json &j, const Damage &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "combat", v.combat);
      opt_to_json(j, "friendly", v.friendly);
      opt_to_json(j, "drowning", v.drowning);
      opt_to_json(j, "environment", v.environment);
      opt_to_json(j, "other", v.other);
      opt_to_json(j, "targetSlot", v.targetSlot);
    }

    void to_json(nlohmann::json &j, const DroppedItem &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["range"] = v.range;
      j["viewSector"] = v.viewSector;
      opt_to_json(j, "lineOfSight", v.lineOfSight);
      opt_to_json(j, "items", v.items);
      opt_to_json(j, "attitudes", v.attitudes);
    }

    void to_json(nlohmann::json &j, const EntityEvent &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["range"] = v.range;
      opt_to_json(j, "searchType", v.searchType);
      opt_to_json(j, "targetSlot", v.targetSlot);
      j["npcGroup"] = v.npcGroup;
      j["eventType"] = v.eventType;
      opt_to_json(j, "flockOnly", v.flockOnly);
    }

    void to_json(nlohmann::json &j, const Flag &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["name"] = v.name;
      opt_to_json(j, "set", v.set);
    }
    void to_json(nlohmann::json &j, const FlockCombatDamage &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "leaderOnly", v.leaderOnly);
    }

    void to_json(nlohmann::json &j, const FlockLeader &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const HasHostileTargetMemory &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const HasInteracted &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const HasTask &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["taskById"] = v.taskById;
    }

    void to_json(nlohmann::json &j, const InAir &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const InWater &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const InflictedDamage &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "target", v.target);
      opt_to_json(j, "friendlyFire", v.friendlyFire);
    }

    void to_json(nlohmann::json &j, const InteractionContext &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["context"] = v.context;
    }

    void to_json(nlohmann::json &j, const IsBackingAway &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const IsBusy &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const Kill &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "targetSlot", v.targetSlot);
    }

    void to_json(nlohmann::json &j, const Leash &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["range"] = v.range;
    }

    void to_json(nlohmann::json &j, const Light &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "lightRange", v.lightRange);
      opt_to_json(j, "skyLightRange", v.skyLightRange);
      opt_to_json(j, "sunlightRange", v.sunlightRange);
      opt_to_json(j, "redLightRange", v.redLightRange);
      opt_to_json(j, "greenLightRange", v.greenLightRange);
      opt_to_json(j, "blueLightRange", v.blueLightRange);
      opt_to_json(j, "targetSlot", v.targetSlot);
    }

    void to_json(nlohmann::json &j, const Mob &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "minRange", v.minRange);
      j["range"] = v.range;
      opt_to_json(j, "lockedOnTarget", v.lockedOnTarget);
      opt_to_json(j, "lockedTargetSlot", v.lockedTargetSlot);
      opt_to_json(j, "autoUnlockTarget", v.autoUnlockTarget);
      opt_to_json(j, "onlyLockedTarget", v.onlyLockedTarget);
      opt_to_json(j, "ignoredTargetSlot", v.ignoredTargetSlot);
      opt_to_json(j, "useProjectedDistance", v.useProjectedDistance);
      opt_to_json(j, "getPlayers", v.getPlayers);
      opt_to_json(j, "getNPCs", v.getNPCs);
      opt_to_json(j, "excludeOwnType", v.excludeOwnType);
      // prioritizer / collector / filters – base-class only, emit type tag
      if (v.prioritizer.has_value())
        j["prioritizer"] = *v.prioritizer;
      if (v.collector.has_value())
        j["collector"] = *v.collector;
      if (v.filters.has_value())
        j["filters"] = *v.filters;
    }

    void to_json(nlohmann::json &j, const Nav &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "navStates", v.navStates);
      opt_to_json(j, "throttleDuration", v.throttleDuration);
      opt_to_json(j, "targetDelta", v.targetDelta);
    }
    void to_json(nlohmann::json &j, const Not &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      if (v.sensor != nullptr)
        j["sensor"] = sensorToJson(*v.sensor);
      opt_to_json(j, "useTargetSlot", v.useTargetSlot);
      opt_to_json(j, "autoUnlockTargetSlot", v.autoUnlockTargetSlot);
    }

    void to_json(nlohmann::json &j, const OnGround &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const Or &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      nlohmann::json arr = nlohmann::json::array();
      for (const auto &s : v.sensors)
        arr.push_back(sensorToJson(*s));
      j["sensors"] = arr;
      opt_to_json(j, "autoUnlockTargetSlot", v.autoUnlockTargetSlot);
    }

    void to_json(nlohmann::json &j, const Path &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "path", v.path);
      opt_to_json(j, "range", v.range);
      opt_to_json(j, "pathType", v.pathType);
    }

    void to_json(nlohmann::json &j, const Player &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "minRange", v.minRange);
      j["range"] = v.range;
      opt_to_json(j, "lockedOnTarget", v.lockedOnTarget);
      opt_to_json(j, "lockedTargetSlot", v.lockedTargetSlot);
      opt_to_json(j, "autoUnlockTarget", v.autoUnlockTarget);
      opt_to_json(j, "onlyLockedTarget", v.onlyLockedTarget);
      opt_to_json(j, "ignoredTargetSlot", v.ignoredTargetSlot);
      opt_to_json(j, "useProjectedDistance", v.useProjectedDistance);
      if (v.prioritizer.has_value())
        j["prioritizer"] = *v.prioritizer;
      if (v.collector.has_value())
        j["collector"] = *v.collector;
      if (v.filters.has_value())
        j["filters"] = *v.filters;
    }

    void to_json(nlohmann::json &j, const Random &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["trueDurationRange"] = v.trueDurationRange;
      j["falseDurationRange"] = v.falseDurationRange;
    }

    void to_json(nlohmann::json &j, const ReadPosition &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["slot"] = v.slot;
      opt_to_json(j, "minRange", v.minRange);
      j["range"] = v.range;
      opt_to_json(j, "useMarkedTarget", v.useMarkedTarget);
    }

    void to_json(nlohmann::json &j, const SearchRay &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["name"] = v.name;
      j["angle"] = v.angle;
      j["range"] = v.range;
      j["blocks"] = v.blocks;
      opt_to_json(j, "minRetestAngle", v.minRetestAngle);
      opt_to_json(j, "minRetestMove", v.minRetestMove);
      opt_to_json(j, "throttleTime", v.throttleTime);
    }

    void to_json(nlohmann::json &j, const Self &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      if (v.filters.has_value())
        j["filters"] = *v.filters;
    }

    void to_json(nlohmann::json &j, const State &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["state"] = v.state;
      opt_to_json(j, "ignoreMissingSetState", v.ignoreMissingSetState);
    }

    void to_json(nlohmann::json &j, const Switch &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["switch"] = v.switchCheck;
    }

    void to_json(nlohmann::json &j, const Target &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "targetSlot", v.targetSlot);
      j["range"] = v.range;
      opt_to_json(j, "autoUnlockTarget", v.autoUnlockTarget);
      if (v.filters.has_value())
        j["filters"] = *v.filters;
    }

    void to_json(nlohmann::json &j, const Time &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["period"] = v.period;
      opt_to_json(j, "checkDay", v.checkDay);
      opt_to_json(j, "checkYear", v.checkYear);
      opt_to_json(j, "scaleDayTimeRange", v.scaleDayTimeRange);
    }

    void to_json(nlohmann::json &j, const Timer &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["name"] = v.name;
      opt_to_json(j, "state", v.state);
      opt_to_json(j, "timeRemainingRange", v.timeRemainingRange);
    }

    void to_json(nlohmann::json &j, const ValueProviderWrapper &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      opt_to_json(j, "passValues", v.passValues);
      if (v.sensor != nullptr)
        j["sensor"] = sensorToJson(*v.sensor);
      j["valueToParameterMappings"] = v.valueToParameterMappings;
    }

    void to_json(nlohmann::json &j, const Weather &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
      j["weathers"] = v.weathers;
    }
  }

  namespace Action
  {
    nlohmann::json actionToJson(const Action &a)
    {
      nlohmann::json j;
      j["type"] = a.type;
      switch (a.type)
      {
      case Type::AddToHostileTargetMemory:
        j = static_cast<const AddToHostileTargetMemory &>(a);
        break;
      case Type::Appearance:
        j = static_cast<const Appearance &>(a);
        break;
      case Type::ApplyEntityEffect:
        j = static_cast<const ApplyEntityEffect &>(a);
        break;
      case Type::CombatAbility:
        j = static_cast<const CombatAbility &>(a);
        break;
      case Type::CompleteTask:
        j = static_cast<const CompleteTask &>(a);
        break;
      case Type::Crouch:
        j = static_cast<const Crouch &>(a);
        break;
      case Type::DelayDespawn:
        j = static_cast<const DelayDespawn &>(a);
        break;
      case Type::Despawn:
        j = static_cast<const Despawn &>(a);
        break;
      case Type::Die:
        j = static_cast<const Die &>(a);
        break;
      case Type::DisplayName:
        j = static_cast<const DisplayName &>(a);
        break;
      case Type::DropItem:
        j = static_cast<const DropItem &>(a);
        break;
      case Type::FlockState:
        j = static_cast<const FlockState &>(a);
        break;
      case Type::FlockTarget:
        j = static_cast<const FlockTarget &>(a);
        break;
      case Type::IgnoreForAvoidance:
        j = static_cast<const IgnoreForAvoidance &>(a);
        break;
      case Type::Inventory:
        j = static_cast<const Inventory &>(a);
        break;
      case Type::JoinFlock:
        j = static_cast<const JoinFlock &>(a);
        break;
      case Type::LeaveFlock:
        j = static_cast<const LeaveFlock &>(a);
        break;
      case Type::LockOnInteractionTarget:
        j = static_cast<const LockOnInteractionTarget &>(a);
        break;
      case Type::Log:
        j = static_cast<const Log &>(a);
        break;
      case Type::ModelAttachment:
        j = static_cast<const ModelAttachment &>(a);
        break;
      case Type::Mount:
        j = static_cast<const Mount &>(a);
        break;
      case Type::Nothing:
        j = static_cast<const Nothing &>(a);
        break;
      case Type::Notify:
        j = static_cast<const Notify &>(a);
        break;
      case Type::OpenBarterShop:
        j = static_cast<const OpenBarterShop &>(a);
        break;
      case Type::OpenShop:
        j = static_cast<const OpenShop &>(a);
        break;
      case Type::OverrideAltitude:
        j = static_cast<const OverrideAltitude &>(a);
        break;
      case Type::OverrideAttitude:
        j = static_cast<const OverrideAttitude &>(a);
        break;
      case Type::ParentState:
        j = static_cast<const ParentState &>(a);
        break;
      case Type::PickUpItem:
        j = static_cast<const PickUpItem &>(a);
        break;
      case Type::PlaceBlock:
        j = static_cast<const PlaceBlock &>(a);
        break;
      case Type::PlaySound:
        j = static_cast<const PlaySound &>(a);
        break;
      case Type::Random:
        j = static_cast<const Random &>(a);
        break;
      case Type::RecomputePath:
        j = static_cast<const RecomputePath &>(a);
        break;
      case Type::ReleaseTarget:
        j = static_cast<const ReleaseTarget &>(a);
        break;
      case Type::Remove:
        j = static_cast<const Remove &>(a);
        break;
      case Type::ResetBlockSensors:
        j = static_cast<const ResetBlockSensors &>(a);
        break;
      case Type::ResetInstructions:
        j = static_cast<const ResetInstructions &>(a);
        break;
      case Type::ResetPath:
        j = static_cast<const ResetPath &>(a);
        break;
      case Type::ResetSearchRays:
        j = static_cast<const ResetSearchRays &>(a);
        break;
      case Type::Role:
        j = static_cast<const Role &>(a);
        break;
      case Type::Sequence:
        j = static_cast<const Sequence &>(a);
        break;
      case Type::SetAlarm:
        j = static_cast<const SetAlarm &>(a);
        break;
      case Type::SetBlockToPlace:
        j = static_cast<const SetBlockToPlace &>(a);
        break;
      case Type::SetFlag:
        j = static_cast<const SetFlag &>(a);
        break;
      case Type::SetInteractable:
        j = static_cast<const SetInteractable &>(a);
        break;
      case Type::SetLeashPosition:
        j = static_cast<const SetLeashPosition &>(a);
        break;
      case Type::SetMarkedTarget:
        j = static_cast<const SetMarkedTarget &>(a);
        break;
      case Type::SetStat:
        j = static_cast<const SetStat &>(a);
        break;
      case Type::StartObjective:
        j = static_cast<const StartObjective &>(a);
        break;
      case Type::State:
        j = static_cast<const State &>(a);
        break;
      case Type::StorePosition:
        j = static_cast<const StorePosition &>(a);
        break;
      case Type::Timeout:
        j = static_cast<const Timeout &>(a);
        break;
      case Type::TimerContinue:
        j = static_cast<const TimerContinue &>(a);
        break;
      case Type::TimerModify:
        j = static_cast<const TimerModify &>(a);
        break;
      case Type::TimerPause:
        j = static_cast<const TimerPause &>(a);
        break;
      case Type::TimerRestart:
        j = static_cast<const TimerRestart &>(a);
        break;
      case Type::TimerStart:
        j = static_cast<const TimerStart &>(a);
        break;
      case Type::TimerStop:
        j = static_cast<const TimerStop &>(a);
        break;
      case Type::ToggleStateEvaluator:
        j = static_cast<const ToggleStateEvaluator &>(a);
        break;
      case Type::TriggerSpawnBeacon:
        j = static_cast<const TriggerSpawnBeacon &>(a);
        break;
      case Type::TriggerSpawners:
        j = static_cast<const TriggerSpawners &>(a);
        break;
      }
      return j;
    }

    void to_json(nlohmann::json &j, const Action &v) { j = actionToJson(v); }

    void to_json(nlohmann::json &j, const WeightedAction &v)
    {
      if (v.action != nullptr)
        j["action"] = actionToJson(*v.action);
      j["weight"] = v.weight;
    }

    void to_json(nlohmann::json &j, const ActionList &v)
    {
      nlohmann::json arr = nlohmann::json::array();
      for (const auto &a : v.actions)
      {
        if (a == nullptr)
          continue;

        arr.push_back(actionToJson(*a));
      }
      j["actions"] = arr;
    }

    void to_json(nlohmann::json &j, const AddToHostileTargetMemory &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
    }

    void to_json(nlohmann::json &j, const Appearance &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["appearance"] = v.appearance;
    }

    void to_json(nlohmann::json &j, const ApplyEntityEffect &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["entityEffect"] = v.entityEffect;
      opt_to_json(j, "useTarget", v.useTarget);
    }
    void to_json(nlohmann::json &j, const CombatAbility &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
    }

    void to_json(nlohmann::json &j, const CompleteTask &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["slot"] = v.slot;
      opt_to_json(j, "animation", v.animation);
      opt_to_json(j, "playAnimation", v.playAnimation);
    }

    void to_json(nlohmann::json &j, const Crouch &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "crouch", v.crouch);
    }

    void to_json(nlohmann::json &j, const DelayDespawn &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["time"] = v.time;
      opt_to_json(j, "shorten", v.shorten);
    }

    void to_json(nlohmann::json &j, const Despawn &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "force", v.force);
    }

    void to_json(nlohmann::json &j, const Die &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
    }

    void to_json(nlohmann::json &j, const DisplayName &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["displayName"] = v.displayName;
    }

    void to_json(nlohmann::json &j, const DropItem &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "delay", v.delay);
      opt_to_json(j, "item", v.item);
      opt_to_json(j, "dropList", v.dropList);
      opt_to_json(j, "throwSpeed", v.throwSpeed);
      opt_to_json(j, "distance", v.distance);
      opt_to_json(j, "dropSector", v.dropSector);
      opt_to_json(j, "pitchHigh", v.pitchHigh);
    }

    void to_json(nlohmann::json &j, const FlockState &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["state"] = v.state;
    }

    void to_json(nlohmann::json &j, const FlockTarget &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "clear", v.clear);
      opt_to_json(j, "targetSlot", v.targetSlot);
    }

    void to_json(nlohmann::json &j, const IgnoreForAvoidance &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["targetSlot"] = v.targetSlot;
    }

    void to_json(nlohmann::json &j, const Inventory &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "operation", v.operation);
      opt_to_json(j, "count", v.count);
      opt_to_json(j, "item", v.item);
      opt_to_json(j, "useTarget", v.useTarget);
      opt_to_json(j, "slot", v.slot);
    }

    void to_json(nlohmann::json &j, const JoinFlock &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "forceJoin", v.forceJoin);
    }

    void to_json(nlohmann::json &j, const LeaveFlock &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
    }

    void to_json(nlohmann::json &j, const LockOnInteractionTarget &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["targetSlot"] = v.targetSlot;
    }

    void to_json(nlohmann::json &j, const Log &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["message"] = v.message;
    }

    void to_json(nlohmann::json &j, const ModelAttachment &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["slot"] = v.slot;
      j["attachment"] = v.attachment;
    }

    void to_json(nlohmann::json &j, const Mount &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["anchorX"] = v.anchorX;
      j["anchorY"] = v.anchorY;
      j["anchorZ"] = v.anchorZ;
      j["movementConfig"] = v.movementConfig;
    }

    void to_json(nlohmann::json &j, const Nothing &v) { j["type"] = v.type; }

    void to_json(nlohmann::json &j, const Notify &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["message"] = v.message;
      j["slot"] = v.slot;
    }

    void to_json(nlohmann::json &j, const OpenBarterShop &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["shop"] = v.shop;
    }

    void to_json(nlohmann::json &j, const OpenShop &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["shop"] = v.shop;
    }

    void to_json(nlohmann::json &j, const OverrideAltitude &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["desiredAltitudeRange"] = v.desiredAltitudeRange;
    }

    void to_json(nlohmann::json &j, const OverrideAttitude &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["attitude"] = v.attitude;
      j["duration"] = v.duration;
    }

    void to_json(nlohmann::json &j, const ParentState &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["state"] = v.state;
    }

    void to_json(nlohmann::json &j, const PickUpItem &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "delay", v.delay);
      j["range"] = v.range;
      opt_to_json(j, "hoover", v.hoover);
      j["items"] = v.items;
    }

    void to_json(nlohmann::json &j, const PlaceBlock &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["range"] = v.range;
      opt_to_json(j, "allowEmptyMaterials", v.allowEmptyMaterials);
    }

    void to_json(nlohmann::json &j, const PlaySound &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["soundEventId"] = v.soundEventId;
    }

    void to_json(nlohmann::json &j, const Random &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["actions"] = v.actions;
    }

    void to_json(nlohmann::json &j, const RecomputePath &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
    }

    void to_json(nlohmann::json &j, const ReleaseTarget &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["targetSlot"] = v.targetSlot;
    }

    void to_json(nlohmann::json &j, const Remove &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "useTarget", v.useTarget);
    }

    void to_json(nlohmann::json &j, const ResetBlockSensors &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["blockSets"] = v.blockSets;
    }

    void to_json(nlohmann::json &j, const ResetInstructions &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "instructions", v.instructions);
    }

    void to_json(nlohmann::json &j, const ResetPath &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
    }

    void to_json(nlohmann::json &j, const ResetSearchRays &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["names"] = v.names;
    }

    void to_json(nlohmann::json &j, const Role &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["role"] = v.role;
      opt_to_json(j, "changeAppearance", v.changeAppearance);
      opt_to_json(j, "state", v.state);
    }

    void to_json(nlohmann::json &j, const Sequence &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "blocking", v.blocking);
      opt_to_json(j, "atomic", v.atomic);
      j["actions"] = v.actions;
    }

    void to_json(nlohmann::json &j, const SetAlarm &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["name"] = v.name;
      j["durationRange"] = v.durationRange;
    }

    void to_json(nlohmann::json &j, const SetBlockToPlace &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["block"] = v.block;
    }

    void to_json(nlohmann::json &j, const SetFlag &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["name"] = v.name;
      opt_to_json(j, "setTo", v.setTo);
    }

    void to_json(nlohmann::json &j, const SetInteractable &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "interactable", v.interactable);
      opt_to_json(j, "hint", v.hint);
      opt_to_json(j, "showPrompt", v.showPrompt);
    }

    void to_json(nlohmann::json &j, const SetLeashPosition &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "toCurrent", v.toCurrent);
      opt_to_json(j, "toTarget", v.toTarget);
    }

    void to_json(nlohmann::json &j, const SetMarkedTarget &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["targetSlot"] = v.targetSlot;
    }

    void to_json(nlohmann::json &j, const SetStat &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["stat"] = v.stat;
      j["value"] = v.value;
      opt_to_json(j, "add", v.add);
    }

    void to_json(nlohmann::json &j, const StartObjective &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["objective"] = v.objective;
    }

    void to_json(nlohmann::json &j, const State &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["state"] = v.state;
      opt_to_json(j, "clearState", v.clearState);
    }

    void to_json(nlohmann::json &j, const StorePosition &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["slot"] = v.slot;
    }

    void to_json(nlohmann::json &j, const Timeout &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["delay"] = v.delay;
      opt_to_json(j, "delayAfter", v.delayAfter);
      if (v.action != nullptr)
        j["action"] = actionToJson(*v.action);
    }

    void to_json(nlohmann::json &j, const TimerContinue &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["name"] = v.name;
    }

    void to_json(nlohmann::json &j, const TimerModify &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["name"] = v.name;
      opt_to_json(j, "addValue", v.addValue);
      opt_to_json(j, "maxValue", v.maxValue);
      opt_to_json(j, "rate", v.rate);
      opt_to_json(j, "setValue", v.setValue);
      opt_to_json(j, "repeating", v.repeating);
    }

    void to_json(nlohmann::json &j, const TimerPause &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["name"] = v.name;
    }

    void to_json(nlohmann::json &j, const TimerRestart &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["name"] = v.name;
    }

    void to_json(nlohmann::json &j, const TimerStart &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["name"] = v.name;
      opt_to_json(j, "startValueRange", v.startValueRange);
      opt_to_json(j, "restartValueRange", v.restartValueRange);
      opt_to_json(j, "rate", v.rate);
      opt_to_json(j, "repeating", v.repeating);
    }

    void to_json(nlohmann::json &j, const TimerStop &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["name"] = v.name;
    }

    void to_json(nlohmann::json &j, const ToggleStateEvaluator &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "enabled", v.enabled);
    }

    void to_json(nlohmann::json &j, const TriggerSpawnBeacon &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      j["beaconSpawn"] = v.beaconSpawn;
      j["range"] = v.range;
      opt_to_json(j, "targetSlot", v.targetSlot);
    }

    void to_json(nlohmann::json &j, const TriggerSpawners &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "once", v.once);
      opt_to_json(j, "spawnMarker", v.spawnMarker);
      j["range"] = v.range;
      opt_to_json(j, "count", v.count);
    }
  }

  namespace BodyMotion
  {
    void to_json(nlohmann::json &j, const BodyMotion &v) { j["type"] = v.type; }

    void to_json(nlohmann::json &j, const AimCharge &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "relativeTurnSpeed", v.relativeTurnSpeed);
    }

    void to_json(nlohmann::json &j, const MaintainDistance &v)
    {
      j["type"] = v.type;
      j["desiredDistanceRange"] = v.desiredDistanceRange;
      opt_to_json(j, "targetDistanceFactor", v.targetDistanceFactor);
      opt_to_json(j, "moveThreshold", v.moveThreshold);
      opt_to_json(j, "relativeForwardsSpeed", v.relativeForwardsSpeed);
      opt_to_json(j, "relativeBackwardsSpeed", v.relativeBackwardsSpeed);
      opt_to_json(j, "moveTowardsSlowdownThreshold", v.moveTowardsSlowdownThreshold);
      opt_to_json(j, "strafingDurationRange", v.strafingDurationRange);
      opt_to_json(j, "strafingFrequencyRange", v.strafingFrequencyRange);
    }

    void to_json(nlohmann::json &j, const MatchLook &v) { j["type"] = v.type; }

    void to_json(nlohmann::json &j, const Nothing &v) { j["type"] = v.type; }

    void to_json(nlohmann::json &j, const Path &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "startAtNearestNode", v.startAtNearestNode);
      opt_to_json(j, "minRelSpeed", v.minRelSpeed);
      opt_to_json(j, "maxRelSpeed", v.maxRelSpeed);
      opt_to_json(j, "direction", v.direction);
      opt_to_json(j, "shape", v.shape);
      opt_to_json(j, "minNodeDelay", v.minNodeDelay);
      opt_to_json(j, "maxNodeDelay", v.maxNodeDelay);
      opt_to_json(j, "useNodeViewDirection", v.useNodeViewDirection);
      opt_to_json(j, "nodePauseScaleRange", v.nodePauseScaleRange);
      opt_to_json(j, "nodePauseExtraPercentRange", v.nodePauseExtraPercentRange);
      opt_to_json(j, "pickRandomAngle", v.pickRandomAngle);
      opt_to_json(j, "viewSegments", v.viewSegments);
    }

    void to_json(nlohmann::json &j, const Sequence &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "looped", v.looped);
      j["motions"] = v.motions;
    }
    void to_json(nlohmann::json &j, const Timer &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "time", v.time);
      j["motion"] = v.motion;
    }

// Shared wander fields helper macro
#define WANDER_TO_JSON(v)                                             \
  opt_to_json(j, "minWalkTime", v.minWalkTime);                       \
  opt_to_json(j, "maxWalkTime", v.maxWalkTime);                       \
  opt_to_json(j, "minHeadingChange", v.minHeadingChange);             \
  opt_to_json(j, "maxHeadingChange", v.maxHeadingChange);             \
  opt_to_json(j, "relaxHeadingChange", v.relaxHeadingChange);         \
  opt_to_json(j, "relativeSpeed", v.relativeSpeed);                   \
  opt_to_json(j, "minMoveDistance", v.minMoveDistance);               \
  opt_to_json(j, "stopDistance", v.stopDistance);                     \
  opt_to_json(j, "testsPerTick", v.testsPerTick);                     \
  opt_to_json(j, "avoidBlockDamage", v.avoidBlockDamage);             \
  opt_to_json(j, "relaxedMoveConstraints", v.relaxedMoveConstraints); \
  opt_to_json(j, "desiredAltitudeWeight", v.desiredAltitudeWeight);

    void to_json(nlohmann::json &j, const Wander &v)
    {
      j["type"] = v.type;
      WANDER_TO_JSON(v)
    }

    void to_json(nlohmann::json &j, const WanderInCircle &v)
    {
      j["type"] = v.type;
      WANDER_TO_JSON(v)
      opt_to_json(j, "radius", v.radius);
      opt_to_json(j, "useSphere", v.useSphere);
    }

    void to_json(nlohmann::json &j, const WanderInRect &v)
    {
      j["type"] = v.type;
      WANDER_TO_JSON(v)
      opt_to_json(j, "width", v.width);
      opt_to_json(j, "depth", v.depth);
    }

#undef WANDER_TO_JSON
  }

  namespace HeadMotion
  {
    void to_json(nlohmann::json &j, const HeadMotion &v) { j["type"] = v.type; }

    void to_json(nlohmann::json &j, const Aim &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "relativeTurnSpeed", v.relativeTurnSpeed);
    }

    void to_json(nlohmann::json &j, const Nothing &v) { j["type"] = v.type; }

    void to_json(nlohmann::json &j, const Observe &v)
    {
      j["type"] = v.type;
      j["angleRange"] = v.angleRange;
      opt_to_json(j, "pauseTimeRange", v.pauseTimeRange);
      opt_to_json(j, "pickRandomAngle", v.pickRandomAngle);
      opt_to_json(j, "viewSegments", v.viewSegments);
      opt_to_json(j, "relativeTurnSpeed", v.relativeTurnSpeed);
    }

    void to_json(nlohmann::json &j, const Sequence &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "looped", v.looped);
      j["motions"] = v.motions;
    }

    void to_json(nlohmann::json &j, const Timer &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "time", v.time);
      j["motion"] = v.motion;
    }

    void to_json(nlohmann::json &j, const Watch &v)
    {
      j["type"] = v.type;
      opt_to_json(j, "relativeTurnSpeed", v.relativeTurnSpeed);
    }
  }

  void to_json(nlohmann::json &j, const Instruction &v)
  {
    j["name"] = v.name;
    opt_to_json(j, "comment", v.comment);
    opt_to_json(j, "enabled", v.enabled);

    if (v.sensor != nullptr)
      j["sensor"] = Sensor::sensorToJson(*v.sensor);
    if (v.bodyMotion.has_value())
      j["bodyMotion"] = v.bodyMotion.value();
    if (v.headMotion.has_value())
      j["headMotion"] = v.headMotion.value();

    nlohmann::json actArr = nlohmann::json::array();
    for (const auto &a : v.actions)
      actArr.push_back(Action::actionToJson(*a));
    if (!actArr.empty())
      j["actions"] = actArr;

    opt_to_json(j, "actionsBlocking", v.actionsBlocking);
    opt_to_json(j, "actionsAtomic", v.actionsAtomic);

    if (!v.instructions.empty())
      j["instructions"] = v.instructions;

    opt_to_json(j, "continue", v.cont);
    opt_to_json(j, "weight", v.weight);
  }

  void to_json(nlohmann::json &j, const StateTransition &v)
  {
    j["priority"] = v.priority;
    j["from"] = v.from;
    j["to"] = v.to;
    opt_to_json(j, "enabled", v.enabled);
  }

  void to_json(nlohmann::json &j, const RequiredAttributes &v)
  {
    j["maxHealth"] = v.maxHealth;
    j["appearance"] = v.appearance;
    j["nameTranslationKey"] = v.nameTranslationKey;

    nlohmann::json busyArr = nlohmann::json::array();
    for (const auto &b : v.busyStates)
      busyArr.push_back(b);
    j["busyStates"] = busyArr;

    nlohmann::json motionArr = nlohmann::json::array();
    for (const auto &m : v.motionControllerList)
    {
      if (m == nullptr)
        continue;
      nlohmann::json motionControllerJSON;
      to_json(motionControllerJSON, *m);
      motionArr.push_back(motionControllerJSON);
    }
    j["motionControllerList"] = motionArr;
  }

  void to_json(nlohmann::json &j, const Attributes &v)
  {
    to_json(j, v.requiredAttributes);

    opt_to_json(j, "initialMotionController", v.initialMotionController);
    opt_to_json(j, "displayNames", v.displayNames);
    opt_to_json(j, "opaqueBlockSet", v.opaqueBlockSet);
    opt_to_json(j, "knockbackScale", v.knockbackScale);
    opt_to_json(j, "inventorySize", v.inventorySize);
    opt_to_json(j, "hotbarSize", v.hotbarSize);
    opt_to_json(j, "offhandSlots", v.offhandSlots);
    opt_to_json(j, "hotbarItems", v.hotbarItems);
    opt_to_json(j, "offhandItems", v.offhandItems);
    opt_to_json(j, "possibleInventoryItems", v.possibleInventoryItems);
    opt_to_json(j, "defaultOffhandSlot", v.defaultOffhandSlot);
    opt_to_json(j, "dropList", v.dropList);
    opt_to_json(j, "startState", v.startState);
    opt_to_json(j, "defaultSubState", v.defaultSubState);
    opt_to_json(j, "collisionDistance", v.collisionDistance);
    opt_to_json(j, "combatConfig", v.combatConfig);
    opt_to_json(j, "invulnerable", v.invulnerable);
    opt_to_json(j, "pickupDropOnDeath", v.pickupDropOnDeath);
    opt_to_json(j, "deathInteraction", v.deathInteraction);
    opt_to_json(j, "defaultPlayerAttitude", v.defaultPlayerAttitude);
    opt_to_json(j, "defaultNPCAttitude", v.defaultNPCAttitude);
    opt_to_json(j, "attitudeGroup", v.attitudeGroup);
    opt_to_json(j, "itemAttitudeGroup", v.itemAttitudeGroup);
    opt_to_json(j, "corpseStaysInFlock", v.corpseStaysInFlock);
    opt_to_json(j, "instructions", v.instructions);
    if (v.interactionInstruction.has_value())
      j["interactionInstruction"] = v.interactionInstruction.value();
    if (v.deathInstruction.has_value())
      j["deathInstruction"] = v.deathInstruction.value();
    opt_to_json(j, "stateTransitions", v.stateTransitions);
    opt_to_json(j, "isMemory", v.isMemory);
    opt_to_json(j, "memoriesCategory", v.memoriesCategory);
    opt_to_json(j, "memoriesNameOverride", v.memoriesNameOverride);
    opt_to_json(j, "spawnLockTime", v.spawnLockTime);
  }

}